[package]
name = "biographer"
version = "0.5.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies]
libc = "*"
rand = "*"
rustc-serialize = "*"

[lib]
name = "biographer"
crate-type = ["dylib"]
