[package]
name = "biographer"
version = "0.5.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies]
libc = "0.1"
rand = "0.3"
rustc-serialize = "0.3"

[lib]
name = "biographer"
crate-type = ["dylib"]
